// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUIHuHxAZL58059DnvC85vk3J2zizKwQ',
    appId: '1:25116014670:web:38b37a711f28c7487d6b1f',
    messagingSenderId: '25116014670',
    projectId: 'notes-app-edd44',
    authDomain: 'notes-app-edd44.firebaseapp.com',
    storageBucket: 'notes-app-edd44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3rfyKbYf3E9C0C9FBLjlvQOemr8GduQ',
    appId: '1:25116014670:android:4efe962d831d83d37d6b1f',
    messagingSenderId: '25116014670',
    projectId: 'notes-app-edd44',
    storageBucket: 'notes-app-edd44.firebasestorage.app',
    databaseURL: 'https://notes-app-edd44-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhVFZBGbZavfeay0u0Q_V99YYv-qmWXXg',
    appId: '1:25116014670:ios:b99f8cdf8c3435457d6b1f',
    messagingSenderId: '25116014670',
    projectId: 'notes-app-edd44',
    storageBucket: 'notes-app-edd44.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhVFZBGbZavfeay0u0Q_V99YYv-qmWXXg',
    appId: '1:25116014670:ios:b99f8cdf8c3435457d6b1f',
    messagingSenderId: '25116014670',
    projectId: 'notes-app-edd44',
    storageBucket: 'notes-app-edd44.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUIHuHxAZL58059DnvC85vk3J2zizKwQ',
    appId: '1:25116014670:web:bbb0fba1daea06f77d6b1f',
    messagingSenderId: '25116014670',
    projectId: 'notes-app-edd44',
    authDomain: 'notes-app-edd44.firebaseapp.com',
    storageBucket: 'notes-app-edd44.firebasestorage.app',
  );
}
